version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alice
      POSTGRES_PASSWORD: wonderland
      POSTGRES_DB: myawesomedb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 54320:5432