import { Product } from "@prisma/client";

const products: Array<Product> =  [
  {
    id:1,
    name: 'Classic Pineapple Cake Eggless [500 grams]',
    slug: 'classic-pineapple-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipNniEC4UzvpZBDXKW_VyNhXBl3AhNzPl5hcLAOq=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:2,
    name: 'Classic Rich Chocolate Glaze Eggless [500 grams]',
    slug: 'classic-rich-cholate-glaze-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipMENNFRUz1jN0KXtRuePe4eY6RfrKOP5OoEn0yP=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:3,
    name: 'Choco Delight lunch box cake [250 gm]',
    slug: 'classic-lunchbox-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipMJJCg0bLmuzL31R5eItbXV1ZcgdB7ay76CaO7M=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:4,
    name: 'Classic Strawberry cake Eggless [500 gm]',
    slug: 'classic-strawberry-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipNniEC4UzvpZBDXKW_VyNhXBl3AhNzPl5hcLAOq=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:5,
    name:'Classic Butterscotch Cake Eggless [ 500 gm]',
    slug: 'classic-butterscotch-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipNniEC4UzvpZBDXKW_VyNhXBl3AhNzPl5hcLAOq=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:6,
    name: 'Classic Chocolate Cake Eggless [500 gm]',
    slug: 'classic-chocolate-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipNniEC4UzvpZBDXKW_VyNhXBl3AhNzPl5hcLAOq=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:7,
    name: 'Classic Vanilla Cake Eggless [500 gm]',
    slug: 'classic-vanilla-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipMNX5AuONCWQEr2KIptjXRbwxD5nArJJFeIB-e5=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:8,
    name: 'Classic Oreo Chocolate Cake Eggless [500 gm]',
    slug: 'classic-oreo-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPl1HmEu9sxrT2Cqm2kQDPHU9bapcu7KOJIyx6E=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:9,
    name: 'Classic Dutch Chocolate Cake Eggless [500 gm]',
    slug: 'classic-dutch-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipNgsvkWZc20XeGYaUsMus6Xy-DjJNKmjD64-8FE=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  },
  {
    id:10,
    name: 'Classic Caramel Cake Eggless [500 gm]',
    slug: 'classic-caramel-cake',
    productCategoryId: 1,
    productTypeId: 1,
    imageUrl: 'https://lh3.googleusercontent.com/p/AF1QipPaDU46up8CCSerDsWXB4pCn8CiSss4w5JPwtp0=s16383-w1024',
    price: 400.00,
    brand: 'JHB',
    rating: 0,
    numReviews: 0,
    countInStock: 2,
    description: 'A popular cake',
  }

];

export default products;

